[build]
buildCommand = "cd data_center/pdc_frontend && npm install && npm run build && cd ../pdc_backend && pip install -r requirements.txt"

[deploy]
startCommand = "cd data_center/pdc_backend && python manage.py migrate --noinput && python manage.py collectstatic --noinput && gunicorn pdc_backend.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120"
