# Generated by Django 5.0.4 on 2026-03-12 11:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='العلامة التجارية')),
                ('name_ar', models.CharField(blank=True, max_length=100, verbose_name='الاسم بالعربية')),
                ('origin_country', models.CharField(blank=True, max_length=100)),
                ('logo_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'علامة تجارية',
                'verbose_name_plural': 'العلامات التجارية',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='الرقم التعريفي (SKU)')),
                ('product_name_ar', models.CharField(max_length=200, verbose_name='اسم المنتج بالعربية')),
                ('product_name_en', models.CharField(blank=True, max_length=200, verbose_name='Product Name in English')),
                ('description_ar', models.TextField(blank=True, verbose_name='الوصف بالعربية')),
                ('origin_country', models.CharField(blank=True, max_length=100, verbose_name='بلد المنشأ')),
                ('status', models.CharField(choices=[('نشط', 'نشط'), ('مسودة', 'مسودة'), ('قيد_المراجعة', 'قيد المراجعة'), ('موقوف', 'موقوف'), ('منتهي', 'منتهي')], default='مسودة', max_length=20, verbose_name='الحالة')),
                ('inventory_type', models.CharField(choices=[('دوري', 'دوري'), ('ستوك', 'ستوك'), ('منتهي', 'منتهي')], default='دوري', max_length=10, verbose_name='نوع المخزون')),
                ('color', models.CharField(blank=True, max_length=100, verbose_name='اللون')),
                ('price_sar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='السعر (ريال)')),
                ('stock_status', models.CharField(blank=True, max_length=50, verbose_name='حالة المخزون (SAP)')),
                ('sap_last_sync', models.DateTimeField(blank=True, null=True, verbose_name='آخر مزامنة SAP')),
                ('ecommerce_url', models.URLField(blank=True, verbose_name='رابط المتجر الإلكتروني')),
                ('attributes', models.JSONField(blank=True, default=dict, verbose_name='السمات الديناميكية')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ النشر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.brand', verbose_name='العلامة التجارية')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='categories.category', verbose_name='الفئة')),
            ],
            options={
                'verbose_name': 'منتج',
                'verbose_name_plural': 'المنتجات',
                'ordering': ['-created_at'],
            },
        ),
    ]
