# Generated by Django 5.0.4 on 2026-03-22 15:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('products', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand'], name='products_pr_brand_i_dc6890_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['origin_country'], name='products_pr_origin__a17580_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['color'], name='products_pr_color_9d5aae_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price_sar'], name='products_pr_price_s_9da284_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='products_pr_created_52f0d7_idx'),
        ),
    ]
