# Generated by Django 5.0.4 on 2026-03-24 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('products', '0003_add_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=50, verbose_name='SKU')),
                ('product_name_ar', models.CharField(max_length=200, verbose_name='اسم المنتج')),
                ('submitter_name', models.CharField(max_length=100, verbose_name='اسم مقدّم الطلب')),
                ('submitter_email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('status', models.CharField(choices=[('pending', 'في الانتظار'), ('in_review', 'قيد المراجعة'), ('pending_approval', 'تحت الموافقة'), ('approved', 'معتمد'), ('rejected', 'مرفوض')], default='pending', max_length=30, verbose_name='الحالة')),
                ('manager_notes', models.TextField(blank=True, verbose_name='ملاحظات المدير')),
                ('admin_notes', models.TextField(blank=True, verbose_name='ملاحظات المدير العام')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_submissions', to=settings.AUTH_USER_MODEL, verbose_name='المدير المسؤول')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='categories.category', verbose_name='التصنيف')),
                ('product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission_request', to='products.product', verbose_name='المنتج المُنشأ')),
            ],
            options={
                'verbose_name': 'طلب إضافة منتج',
                'verbose_name_plural': 'طلبات إضافة منتجات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r2_key', models.CharField(max_length=500)),
                ('r2_url', models.URLField(max_length=1000)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.productsubmission')),
            ],
        ),
    ]
