# Generated by Django 5.0.4 on 2026-03-25 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productsubmission_submissionimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsubmission',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية للمنتج'),
        ),
    ]
