# Generated by Django 5.0.4 on 2026-03-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create_product', 'إنشاء منتج'), ('update_product', 'تعديل منتج'), ('publish_product', 'نشر منتج'), ('delete_product', 'حذف منتج'), ('upload_image', 'رفع صورة'), ('approve_image', 'اعتماد صورة'), ('reject_image', 'رفض صورة'), ('generate_description', 'توليد وصف AI'), ('generate_image', 'توليد صورة AI'), ('sap_sync', 'مزامنة SAP'), ('generate_catalog', 'توليد كتالوج PDF'), ('user_login', 'تسجيل دخول'), ('create_user', 'إنشاء مستخدم'), ('update_user', 'تعديل مستخدم')], max_length=30, verbose_name='الإجراء')),
                ('content_type', models.CharField(blank=True, max_length=50, verbose_name='نوع الكائن')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='معرف الكائن')),
                ('object_repr', models.CharField(blank=True, max_length=200, verbose_name='وصف الكائن')),
                ('details', models.TextField(blank=True, verbose_name='التفاصيل')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='الوقت')),
            ],
            options={
                'verbose_name': 'سجل عملية',
                'verbose_name_plural': 'سجل العمليات',
                'ordering': ['-created_at'],
            },
        ),
    ]
