# Generated by Django 5.0.4 on 2026-03-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('ai_reviewed', 'مراجعة AI'), ('human_reviewing', 'مراجعة بشرية'), ('approved', 'مُعتمد'), ('rejected', 'مرفوض')], default='pending', max_length=20)),
                ('submitted_data', models.JSONField(default=dict, verbose_name='البيانات المُقدَّمة')),
                ('ai_validation_result', models.JSONField(blank=True, null=True, verbose_name='نتيجة مراجعة AI')),
                ('ai_score', models.IntegerField(blank=True, null=True, verbose_name='درجة AI')),
                ('ai_auto_approve_eligible', models.BooleanField(default=False)),
                ('reviewer_notes', models.TextField(blank=True, verbose_name='ملاحظات المراجع')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'طلب اعتماد منتج',
                'verbose_name_plural': 'طلبات اعتماد المنتجات',
                'ordering': ['-created_at'],
            },
        ),
    ]
