# Generated by Django 5.0.4 on 2026-03-22 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productapprovalrequest',
            name='previous_status',
            field=models.CharField(blank=True, max_length=50, verbose_name='الحالة السابقة للمنتج'),
        ),
        migrations.AddField(
            model_name='productapprovalrequest',
            name='request_type',
            field=models.CharField(choices=[('new_product', 'منتج جديد'), ('edit_product', 'تعديل منتج')], default='new_product', max_length=20, verbose_name='نوع الطلب'),
        ),
    ]
