# Generated by Django 5.0.4 on 2026-03-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LookupValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup_type', models.CharField(choices=[('country', 'بلد المنشأ'), ('color', 'اللون')], max_length=50, verbose_name='نوع القائمة')),
                ('name_ar', models.CharField(max_length=100, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='الاسم بالإنجليزية')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'قيمة إعداد',
                'verbose_name_plural': 'قيم الإعدادات',
                'ordering': ['lookup_type', 'order', 'name_ar'],
                'unique_together': {('lookup_type', 'name_ar')},
            },
        ),
    ]
