# Generated by Django 5.0.4 on 2026-03-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompletenessReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.FloatField(default=0, verbose_name='نسبة الاكتمال الإجمالية %')),
                ('total_products', models.IntegerField(default=0, verbose_name='إجمالي المنتجات')),
                ('complete_products', models.IntegerField(default=0, verbose_name='المنتجات المكتملة')),
                ('category_scores', models.JSONField(default=dict, verbose_name='نسب الاكتمال بالفئة')),
                ('critical_gaps', models.JSONField(default=list, verbose_name='الفجوات الحرجة')),
                ('recommendations', models.JSONField(default=list, verbose_name='التوصيات')),
                ('missing_lifestyle_images', models.IntegerField(default=0, verbose_name='صور ديكورية ناقصة')),
                ('missing_main_images', models.IntegerField(default=0, verbose_name='صور رئيسية ناقصة')),
                ('missing_sap_data', models.IntegerField(default=0, verbose_name='بيانات SAP ناقصة')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التقرير')),
            ],
            options={
                'verbose_name': 'تقرير الاكتمال',
                'verbose_name_plural': 'تقارير الاكتمال',
                'ordering': ['-generated_at'],
            },
        ),
    ]
