# Generated by Django 5.0.4 on 2026-03-12 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(max_length=100, verbose_name='Name in English')),
                ('slug', models.SlugField(unique=True, verbose_name='المعرف')),
                ('description_ar', models.TextField(blank=True, verbose_name='الوصف')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='أيقونة Lucide')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'فئة',
                'verbose_name_plural': 'الفئات',
                'ordering': ['order', 'name_ar'],
            },
        ),
        migrations.CreateModel(
            name='CategoryAttributeSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(max_length=50, verbose_name='مفتاح الحقل')),
                ('field_label_ar', models.CharField(max_length=100, verbose_name='اسم الحقل بالعربية')),
                ('field_label_en', models.CharField(blank=True, max_length=100, verbose_name='Field Name in English')),
                ('field_type', models.CharField(choices=[('text', 'نص حر'), ('number', 'رقم'), ('select', 'قائمة اختيار'), ('multi_select', 'اختيار متعدد'), ('boolean', 'نعم/لا'), ('dimensions', 'أبعاد')], default='text', max_length=20)),
                ('options', models.JSONField(blank=True, default=list, verbose_name='خيارات القائمة')),
                ('is_required', models.BooleanField(default=False, verbose_name='مطلوب')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='الوحدة (سم، م²...)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('help_text_ar', models.CharField(blank=True, max_length=200, verbose_name='نص مساعد')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_schemas', to='categories.category')),
            ],
            options={
                'verbose_name': 'حقل ديناميكي للفئة',
                'verbose_name_plural': 'الحقول الديناميكية للفئات',
                'ordering': ['category', 'order'],
                'unique_together': {('category', 'field_key')},
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100)),
                ('name_en', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField()),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='categories.category')),
            ],
            options={
                'verbose_name': 'فئة فرعية',
                'verbose_name_plural': 'الفئات الفرعية',
                'unique_together': {('category', 'slug')},
            },
        ),
    ]
