# Generated by Django 5.0.4 on 2026-04-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryattributeschema',
            name='options_en',
            field=models.JSONField(blank=True, default=list, verbose_name='List Options (English)'),
        ),
        migrations.AddField(
            model_name='categoryattributeschema',
            name='unit_en',
            field=models.CharField(blank=True, max_length=20, verbose_name='Unit in English (cm, m²...)'),
        ),
        migrations.AlterField(
            model_name='categoryattributeschema',
            name='options',
            field=models.JSONField(blank=True, default=list, verbose_name='خيارات القائمة (عربي)'),
        ),
        migrations.AlterField(
            model_name='categoryattributeschema',
            name='unit',
            field=models.CharField(blank=True, max_length=20, verbose_name='الوحدة بالعربية (سم، م²...)'),
        ),
    ]
