# Generated by Django 5.0.4 on 2026-03-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(choices=[('main', 'الصورة الرئيسية'), ('gallery', 'معرض الصور'), ('detail', 'صورة التفاصيل'), ('lifestyle', 'صورة ديكورية'), ('technical', 'مخطط تقني')], default='gallery', max_length=15, verbose_name='نوع الصورة')),
                ('r2_key', models.CharField(max_length=300, verbose_name='مسار R2')),
                ('r2_url', models.URLField(blank=True, verbose_name='رابط الصورة')),
                ('original_filename', models.CharField(blank=True, max_length=200, verbose_name='اسم الملف الأصلي')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='العرض (بكسل)')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='الارتفاع (بكسل)')),
                ('file_size_kb', models.PositiveIntegerField(blank=True, null=True, verbose_name='حجم الملف (كيلوبايت)')),
                ('status', models.CharField(choices=[('pending_review', 'قيد المراجعة'), ('approved', 'مُعتمدة'), ('rejected', 'مرفوضة')], default='pending_review', max_length=15, verbose_name='الحالة')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_ai_generated', models.BooleanField(default=False, verbose_name='مُولَّدة بالـ AI')),
                ('ai_prompt_used', models.TextField(blank=True, verbose_name='البرومبت المُستخدم')),
                ('ai_generation_task_id', models.CharField(blank=True, max_length=100, verbose_name='معرف مهمة Celery')),
                ('has_bg_removed', models.BooleanField(default=False, verbose_name='تم إزالة الخلفية')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_notes', models.TextField(blank=True, verbose_name='ملاحظات المراجع')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'صورة منتج',
                'verbose_name_plural': 'صور المنتجات',
                'ordering': ['product', 'image_type', 'order'],
            },
        ),
    ]
