# Generated by Django 5.0.4 on 2026-03-26 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_initial'),
        ('products', '0005_add_extra_data_to_submission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DecorativeGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_image_url', models.URLField(verbose_name='رابط الصورة المصدر')),
                ('status', models.CharField(choices=[('analyzing', 'جاري التحليل'), ('analyzed', 'تم التحليل'), ('generating', 'جاري التوليد'), ('completed', 'مكتمل'), ('failed', 'فشل')], default='analyzing', max_length=15, verbose_name='الحالة')),
                ('vision_analysis', models.JSONField(blank=True, default=dict, verbose_name='نتيجة تحليل الرؤية')),
                ('generation_settings', models.JSONField(blank=True, default=dict, verbose_name='إعدادات التوليد')),
                ('prompt_used', models.TextField(blank=True, verbose_name='البرومبت المُستخدم')),
                ('negative_prompt', models.TextField(blank=True, verbose_name='البرومبت السلبي')),
                ('kie_task_id', models.CharField(blank=True, max_length=100, verbose_name='معرف مهمة Kie.ai')),
                ('result_image_url', models.URLField(blank=True, verbose_name='رابط الصورة الناتجة')),
                ('error_message', models.TextField(blank=True, verbose_name='رسالة الخطأ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decorative_generations', to=settings.AUTH_USER_MODEL, verbose_name='أُنشئ بواسطة')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decorative_generations', to='products.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'توليد صورة ديكورية',
                'verbose_name_plural': 'توليد صور ديكورية',
                'ordering': ['-created_at'],
            },
        ),
    ]
