# Generated by Django 5.0.4 on 2026-04-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_decorative_generation'),
    ]

    operations = [
        migrations.AddField(
            model_name='decorativegeneration',
            name='is_multi_product',
            field=models.BooleanField(default=False, verbose_name='مشهد متعدد المنتجات'),
        ),
        migrations.AddField(
            model_name='decorativegeneration',
            name='multi_product_data',
            field=models.JSONField(blank=True, default=list, help_text='List of {role, image_url, product_id, analysis} for multi-product scenes', verbose_name='بيانات المنتجات المتعددة'),
        ),
    ]
